'use client';
import { useState, useTransition } from 'react';
import { Copy, Loader2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { createRoleplaySession, requestBaseRoleplayUpload } from '@/app/actions/roleplays';

export function CreateRoleplayForm({ interpreters, candidates, initialCandidateId }: { interpreters: { id: number; name: string; email: string | null }[]; candidates: { id: number; name: string; email: string }[]; initialCandidateId?: number }) {
  const [subject, setSubject] = useState<'interpreter' | 'candidate'>(initialCandidateId ? 'candidate' : 'interpreter'); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState<string | null>(null); const [link, setLink] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  function submit(form: FormData) { startTransition(async () => { if (!file) { setMessage('Selecciona el audio base.'); return; } const prep = await requestBaseRoleplayUpload({ size: file.size, type: file.type }); if (!prep.success || !prep.path || !prep.token) { setMessage(prep.error ?? 'No se pudo preparar la carga.'); return; } const client = createClient(); if (!client) { setMessage('La configuración de Storage no está disponible.'); return; } const { error } = await client.storage.from('roleplay-audio').uploadToSignedUrl(prep.path, prep.token, file, { contentType: file.type }); if (error) { setMessage('No se pudo subir el audio base.'); return; } const result = await createRoleplaySession({ interpreterId: subject === 'interpreter' ? Number(form.get('participantId')) : undefined, recruitmentCandidateId: subject === 'candidate' ? Number(form.get('participantId')) : undefined, baseAudioPath: prep.path }); if (!result.success || !result.sessionId) { setMessage(result.error ?? 'No se pudo crear la sesión.'); return; } const origin = window.location.origin; setLink(result.inviteUrl ? `${origin}${result.inviteUrl}` : `${origin}/roleplays/${result.sessionId}`); setMessage('Roleplay creado correctamente.'); }); }
  return <form action={submit} className="max-w-2xl space-y-6 rounded-2xl border border-white/10 bg-slate-900/60 p-6 text-white"><div className="flex gap-5"><label><input type="radio" checked={subject === 'interpreter'} onChange={() => setSubject('interpreter')} /> Intérprete</label><label><input type="radio" checked={subject === 'candidate'} onChange={() => setSubject('candidate')} /> Candidato</label></div><label className="block text-sm font-medium">Participante<select name="participantId" defaultValue={initialCandidateId} required className="mt-2 block w-full rounded-lg border border-white/10 bg-slate-950 p-3">{(subject === 'interpreter' ? interpreters : candidates).map((person) => <option key={person.id} value={person.id}>{person.name} — {person.email}</option>)}</select></label><label className="block text-sm font-medium">Audio base<input required accept="audio/webm,audio/mpeg,audio/mp4,audio/ogg" onChange={(event) => setFile(event.target.files?.[0] ?? null)} type="file" className="mt-2 block w-full text-sm" /></label>{file && <audio controls className="w-full" src={URL.createObjectURL(file)} />}<button disabled={pending} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold disabled:bg-slate-700">{pending && <Loader2 className="animate-spin" size={18} />}Crear roleplay</button>{message && <p className="rounded-lg bg-white/5 p-3 text-sm">{message}</p>}{link && <div className="flex gap-2 rounded-lg border border-emerald-500/30 p-3 text-sm break-all"><span>{link}</span><button type="button" onClick={() => navigator.clipboard.writeText(link)} aria-label="Copiar enlace"><Copy size={16} /></button></div>}</form>;
}
